/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Mirko
 * Created: 23-ago-2017

 Connessione NetBeans:
      Username: mirkogiacalone
      Password: Mirko123
*/


CREATE TABLE Users (
    Id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(20),
    cognome VARCHAR(20),
    UrlImgPro VARCHAR(100),
    frase VARCHAR(250),
    datan DATE,
    password VARCHAR(20) NOT NULL,
    PotereUtente VARCHAR(20),
    UNIQUE(nome)
);

CREATE TABLE Groups (
    Id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(20),
    UrlImgPro VARCHAR(100),
    argomento VARCHAR(100),
    creatore INTEGER REFERENCES Users(Id),
    UNIQUE(Nome)
);


CREATE TABLE Users_Groups(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_u INTEGER REFERENCES Users(Id),
    Id_g INTEGER REFERENCES Groups(Id) 
);

CREATE TABLE Post (
    Id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autore INTEGER REFERENCES Users(Id),
    destinatario INTEGER REFERENCES Users(Id),
    gruppo INTEGER REFERENCES Groups(Id),
    content VARCHAR(200),
    tipo VARCHAR(20),
    allegato VARCHAR(256)    
);

INSERT INTO Users (Id, nome, cognome, UrlImgPro, frase, datan, password, PotereUtente) VALUES 
( default,'UtenteUno','UtenteUno','immagini/iconautente.jpg','Frase utente1','2017-01-13','pswutente1','SUPERUSER');

INSERT INTO Users (Id, nome, cognome, UrlImgPro, frase, datan, password, PotereUtente) VALUES 
( default,'UtenteDue','UtenteDue','immagini/iconautente.jpg','Frase utente2','2017-01-13','pswutente2','USER');

INSERT INTO Users (Id, nome, cognome, UrlImgPro, frase, datan, password, PotereUtente) VALUES 
( default,'UtenteTre','UtenteTre','immagini/iconautente.jpg','Frase utente3','2017-01-13','pswutente3','USER');

INSERT INTO Users (Id, nome, cognome, UrlImgPro, frase, datan, password, PotereUtente) VALUES 
( default,'Incompleto','Incompleto','immagini/iconautente.jpg',NULL,'2017-01-13','pswincompleto','USER');


INSERT INTO Groups (Id, creatore, argomento, nome, UrlImgPro) VALUES 
( default,1,'Argomento 1','GruppoUno','immagini/clock.png');

INSERT INTO Groups (Id, creatore, argomento, nome, UrlImgPro) VALUES 
( default,2,'Argomento 2','GruppoDue','immagini/clock.png');

INSERT INTO Groups (Id, creatore, argomento, nome, UrlImgPro) VALUES 
( default,3,'Argomento 3','GruppoTre','immagini/clock.png');


INSERT INTO Users_Groups(Id, Id_u, Id_g) VALUES 
(default, 1, 1), (default, 1, 2), (default, 1, 3), (default, 2, 2), (default, 2, 3), (default, 3, 3);


INSERT INTO Post (Id, autore, destinatario, gruppo, content, tipo, allegato)VALUES
(default, 1, NULL, NULL, 'Contenuto Post 1', 'TEXT', NULL),
(default, 1, NULL, NULL, 'Altro post', 'TEXT', NULL), 
(default, 1, NULL, 2, 'Post gruppo', 'TEXT', NULL), 
(default, 2, NULL, NULL, NULL, 'IMAGE', 'immagini/imglink.png'),
(default, 3, NULL, NULL, NULL, 'URL', 'http://www.html.it/');

CREATE TABLE Users_Users(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_ua INTEGER REFERENCES Users(Id),
    Id_ub INTEGER REFERENCES Users(Id)
);

INSERT INTO Users_Users(Id, Id_ua, Id_ub)VALUES 
(default, 1, 2), (default, 2, 3);


